name: Test whether Cyberpanel works
on: push

jobs:
  centos7:
    name: Cyberpanel on Centos 7
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
      options: --user root
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install Cron
        run: |
          yum update -y
          yum install crontabs python3 python3-devel -y
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -v 127.0.0.1:8090
        shell: bash
      - name: Keep the container running
        run: while true; sleep 2; done
        shell: bash
  centos8:
    name: Cyberpanel on Centos 8
    runs-on: ubuntu-latest
    container:
      image: centos:centos8
      options: --user root
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Fix missing mirrorlist (Bug in CentOS 8 Container)
        run: |
          cd /etc/yum.repos.d/ 
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - name: Install Cron
        run: |
          yum update -y
          yum install crontabs python3 python3-devel -y
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -v https://127.0.0.1:8090
        shell: bash
      - name: Keep the container running
        run: while true; sleep 2; done
        shell: bash
  almalinux8:
    name: Cyberpanel on Almalinux 8
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:almalinux-8
      options: --user root --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install wget curl crontabs python3 python3-devel -y 
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
  rockylinux:
    name: Cyberpanel on Rockylinux
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
      options: --user root
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install wget curl cronie python3 python3-devel -y 
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
  openeuler2003:
    name: Cyberpanel on Openeuler 20.03
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:20.03
      options: --user root
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install wget curl cronie python3 python3-devel -y 
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
  openeuler2203:
    name: Cyberpanel on Openeuler 22.03
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:22.03
      options: --user root
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install wget curl cronie python3 python3-devel -y 
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
  ubuntu1804:
    name: Cyberpanel on Ubuntu 18.04
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:ubuntu-18.04
      options: --user root --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          apt update -y 
          apt install -y wget curl cron 
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n5\n5\n5\n5" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
  ubuntu2004:
    name: Cyberpanel on Ubuntu 20.04
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:ubuntu-20.04
      options: --user root --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          apt update -y
          apt install -y wget curl cron
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Check if installation was succesful
        run: curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8090
        shell: bash
      - name: Sleep indefinite to be able to access the GUI
        run: sleep infinity
