name: Test whether Cyberpanel works
on: push

jobs:
  centos7:
    name: Cyberpanel on Centos 7
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
      ports:
        - 8090:8090
      options: --user root --sysctl net.ipv4.ip_forward=1
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install Cron
        run: |
          yum update -y
          yum install crontabs python3 python3-devel openssl -y
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
        shell: bash
  centos8:
    name: Cyberpanel on Centos 8
    runs-on: ubuntu-latest
    container:
      image: centos:centos8
      ports:
        - 8090:8090
      options: --user root --sysctl net.ipv4.ip_forward=1
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Fix missing mirrorlist (Bug in CentOS 8 Container)
        run: |
          cd /etc/yum.repos.d/ 
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
      - name: Install Cron
        run: |
          yum update -y
          yum install crontabs python3 python3-devel -y
          crontab -l | { cat; } | crontab -
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
        shell: bash
  almalinux8:
    name: Cyberpanel on Almalinux 8
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:almalinux-8
      ports:
        - 8090:8090
      options: --user root --privileged --sysctl net.ipv4.ip_forward=1
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install crontabs python3 python3-devel systemd -y
          (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);
          rm -f /lib/systemd/system/multi-user.target.wants/*;
          rm -f /etc/systemd/system/*.wants/*;
          rm -f /lib/systemd/system/local-fs.target.wants/*;
          rm -f /lib/systemd/system/sockets.target.wants/*udev*;
          rm -f /lib/systemd/system/sockets.target.wants/*initctl*;
          rm -f /lib/systemd/system/basic.target.wants/*;
          rm -f /lib/systemd/system/anaconda.target.wants/*;
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
  rockylinux:
    name: Cyberpanel on Rockylinux
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
      ports:
        - 8090:8090
      options: --user root --sysctl net.ipv4.ip_forward=1
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install crontabs cronie python3 python3-devel findutils systemd -y
          (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);
          rm -f /lib/systemd/system/multi-user.target.wants/*;
          rm -f /etc/systemd/system/*.wants/*;
          rm -f /lib/systemd/system/local-fs.target.wants/*;
          rm -f /lib/systemd/system/sockets.target.wants/*udev*;
          rm -f /lib/systemd/system/sockets.target.wants/*initctl*;
          rm -f /lib/systemd/system/basic.target.wants/*;
          rm -f /lib/systemd/system/anaconda.target.wants/*;
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
  openeuler2003:
    name: Cyberpanel on Openeuler 20.03
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:20.03
      ports:
        - 8090:8090
      options: --user root --sysctl net.ipv4.ip_forward=1
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install crontabs cronie python3 python3-devel -y
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
  openeuler2203:
    name: Cyberpanel on Openeuler 22.03
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:22.03
      options: --user root --sysctl net.ipv4.ip_forward=1
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          yum update -y
          yum install crontabs cronie python3 python-pip -y
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
        shell: bash
  ubuntu1804:
    name: Cyberpanel on Ubuntu 18.04
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:ubuntu-18.04
      ports:
        - 8090:8090
      options: --user root --privileged --sysctl net.ipv4.ip_forward=1
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: |
          echo HOME=/root | tee -a $GITHUB_ENV
          echo DEBIAN_FRONTEND=noninteractive | tee -a $GITHUB_ENV
      - name: Install wget, curl and cron
        run: |
          apt update -y 
          apt install -y wget curl cron systemd
          (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);
          rm -f /lib/systemd/system/multi-user.target.wants/*;
          rm -f /etc/systemd/system/*.wants/*;
          rm -f /lib/systemd/system/local-fs.target.wants/*;
          rm -f /lib/systemd/system/sockets.target.wants/*udev*;
          rm -f /lib/systemd/system/sockets.target.wants/*initctl*;
          rm -f /lib/systemd/system/basic.target.wants/*;
          rm -f /lib/systemd/system/anaconda.target.wants/*;
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
        shell: bash
  ubuntu2004:
    name: Cyberpanel on Ubuntu 20.04
    runs-on: ubuntu-latest
    container:
      image: fauust/docker-systemd:ubuntu-20.04
      ports:
        - 8090:8090
      options: --user root --privileged --sysctl net.ipv4.ip_forward=1
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
      env:
        USER: cyberpanel-dynamic
        REPO: cyberpanel
        BRANCH: stable
        UPGRADE_BRANCH: v2.3.2
        GITHUB_HOME: /root
        GITHUB_RUNNER_HOME: /root
        HOME: /root
    steps:
      - name: set home env
        shell: bash
        run: "echo HOME=/root | tee -a $GITHUB_ENV"
      - name: Install wget, curl and cron
        run: |
          apt update -y
          apt install -y wget curl cron systemd
          (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done);
          rm -f /lib/systemd/system/multi-user.target.wants/*;
          rm -f /etc/systemd/system/*.wants/*;
          rm -f /lib/systemd/system/local-fs.target.wants/*;
          rm -f /lib/systemd/system/sockets.target.wants/*udev*;
          rm -f /lib/systemd/system/sockets.target.wants/*initctl*;
          rm -f /lib/systemd/system/basic.target.wants/*;
          rm -f /lib/systemd/system/anaconda.target.wants/*;
      - name: Install Cyberpanel from current Repository
        run: printf "\n1\n1\n\n\n\n\n\n" | bash <(curl https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh || wget -O - https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/install.sh)
        shell: bash
      - name: Keep the container running
        run: sleep 30m
        shell: bash
